export { default as WriteKanjiScreen } from "./writeKanji/WriteKanji";
export { default as PracticeKanjiScreen } from "./practiceKanji/PracticeKanji";
export { default as CourseStudyScreen } from "./courseStudy/CourseStudy";
export { default as Course } from "./course/Course";
export { default as TestOnline } from "./testOnline/TestOnline";
export { default as QuestionTestOnline } from "./questionTestOnline/QuestionTestOnline";
export { default as RankTestOnline } from "./rankTestOnline/RankTestOnline";
export { default as Profile } from "./profile/Profile";
export { default as Teacher } from "./teacher/Teacher";
